public enum SceneIndex
{
    INITIALIZATION_SCENE = 0,
    LOBBY_SCENE = 1,
    METAHOME_EXTERIOR_SCENE = 2,
    METAHOME_INTERIOR_SCENE = 3,
    METAPORT_ORBIT = 4,
    METAPORT_LOADER = 3,
    MAIN_MENU_SCENE = 99
}